from Tkinter import *

root = Tk()
root.resizable(width=False, height=False)
root.geometry("500x300")
frame = Frame(root)
titleLabel = Label(frame, text="CHEERS", fg="black")
titleLabel.grid(row=0, column=1)
radiusLabel = Label(frame, text="Enter Radius", fg="black")
radiusLabel.grid(row=1, column=0, sticky=E)
entry_1 = Entry(frame)
entry_1.grid(row=1, column=1)
lengthLabel = Label(frame, text="Output Length", fg="black")
lengthLabel.grid(row=2, column=0, sticky=E)
entry_2 = Entry(frame)
entry_2.grid(row=2, column=1)
lengthButton = Button(frame, text="Calculate Length", fg="black")
lengthButton.grid(row=3, column=0, sticky=E)
XMLButton = Button(frame, text="Save to XML ", fg="black")
XMLButton.grid(row=3, column=1, sticky=E)
frame.pack()
#frame.pack(fill=None, expand=False)
root.mainloop()
